---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: cf-deployment
- name: relint-envs

params:
  DAYS_LEFT_THRESHOLD: 16
  PATH_TO_VERIFY: relint-envs

run:
  path: cf-deployment/ci/tasks/check-certs/task
