- type: replace
  path: /addons?/-
  value:
    include:
      stemcell:
      - os: ubuntu-trusty
    jobs:
    - name: bosh-dns
      properties:
        aliases:
          _.cell.service.cf.internal:
          - _.diego-cell.((network_name)).((deployment_name)).bosh
          - _.windows-cell.((network_name)).((deployment_name)).bosh
          - _.windows2016-cell.((network_name)).((deployment_name)).bosh
          - _.isolated-diego-cell.((network_name)).((deployment_name)).bosh
          auctioneer.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          bbs.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          bits-service.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          blobstore.service.cf.internal:
          - '*.blobstore.((network_name)).((deployment_name)).bosh'
          - '*.singleton-blobstore.((network_name)).((deployment_name)).bosh'
          cc-uploader.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          cloud-controller-ng.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          consul.service.cf.internal:
          - '*.consul.((network_name)).((deployment_name)).bosh'
          credhub.service.cf.internal:
          - '*.credhub.((network_name)).((deployment_name)).bosh'
          doppler.service.cf.internal:
          - '*.doppler.((network_name)).((deployment_name)).bosh'
          file-server.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          gorouter.service.cf.internal:
          - '*.router.((network_name)).((deployment_name)).bosh'
          locket.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          loggregator-trafficcontroller.service.cf.internal:
          - '*.log-api.((network_name)).((deployment_name)).bosh'
          policy-server.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          reverse-log-proxy.service.cf.internal:
          - '*.log-api.((network_name)).((deployment_name)).bosh'
          routing-api.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          silk-controller.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          sql-db.service.cf.internal:
          - '*.mysql.((network_name)).((deployment_name)).bosh'
          - '*.postgres.((network_name)).((deployment_name)).bosh'
          - '*.database.((network_name)).((deployment_name)).bosh'
          ssh-proxy.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          tps.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          uaa.service.cf.internal:
          - '*.uaa.((network_name)).((deployment_name)).bosh'
        api:
          client:
            tls: ((dns_api_client_tls))
          server:
            tls: ((dns_api_server_tls))
      release: bosh-dns
    name: bosh-dns
- type: replace
  path: /addons/-
  value:
    include:
      stemcell:
      - os: windows2012R2
    jobs:
    - name: bosh-dns-windows
      properties:
        aliases:
          _.cell.service.cf.internal:
          - _.diego-cell.((network_name)).((deployment_name)).bosh
          - _.windows-cell.((network_name)).((deployment_name)).bosh
          - _.windows2016-cell.((network_name)).((deployment_name)).bosh
          - _.isolated-diego-cell.((network_name)).((deployment_name)).bosh
          auctioneer.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          bbs.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          bits-service.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          blobstore.service.cf.internal:
          - '*.blobstore.((network_name)).((deployment_name)).bosh'
          - '*.singleton-blobstore.((network_name)).((deployment_name)).bosh'
          cc-uploader.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          cloud-controller-ng.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          consul.service.cf.internal:
          - '*.consul.((network_name)).((deployment_name)).bosh'
          credhub.service.cf.internal:
          - '*.credhub.((network_name)).((deployment_name)).bosh'
          doppler.service.cf.internal:
          - '*.doppler.((network_name)).((deployment_name)).bosh'
          file-server.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          gorouter.service.cf.internal:
          - '*.router.((network_name)).((deployment_name)).bosh'
          locket.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          loggregator-trafficcontroller.service.cf.internal:
          - '*.log-api.((network_name)).((deployment_name)).bosh'
          policy-server.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          reverse-log-proxy.service.cf.internal:
          - '*.log-api.((network_name)).((deployment_name)).bosh'
          routing-api.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          silk-controller.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          sql-db.service.cf.internal:
          - '*.mysql.((network_name)).((deployment_name)).bosh'
          - '*.postgres.((network_name)).((deployment_name)).bosh'
          - '*.database.((network_name)).((deployment_name)).bosh'
          ssh-proxy.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          tps.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          uaa.service.cf.internal:
          - '*.uaa.((network_name)).((deployment_name)).bosh'
        api:
          client:
            tls: ((dns_api_client_tls))
          server:
            tls: ((dns_api_server_tls))
      release: bosh-dns
    name: bosh-dns-windows2012
- type: replace
  path: /addons/-
  value:
    include:
      stemcell:
      - os: windows2016
    jobs:
    - name: bosh-dns-windows
      properties:
        aliases:
          _.cell.service.cf.internal:
          - _.diego-cell.((network_name)).((deployment_name)).bosh
          - _.windows-cell.((network_name)).((deployment_name)).bosh
          - _.windows2016-cell.((network_name)).((deployment_name)).bosh
          - _.isolated-diego-cell.((network_name)).((deployment_name)).bosh
          auctioneer.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          bbs.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          bits-service.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          blobstore.service.cf.internal:
          - '*.blobstore.((network_name)).((deployment_name)).bosh'
          - '*.singleton-blobstore.((network_name)).((deployment_name)).bosh'
          cc-uploader.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          cloud-controller-ng.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          consul.service.cf.internal:
          - '*.consul.((network_name)).((deployment_name)).bosh'
          credhub.service.cf.internal:
          - '*.credhub.((network_name)).((deployment_name)).bosh'
          doppler.service.cf.internal:
          - '*.doppler.((network_name)).((deployment_name)).bosh'
          file-server.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          gorouter.service.cf.internal:
          - '*.router.((network_name)).((deployment_name)).bosh'
          locket.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          loggregator-trafficcontroller.service.cf.internal:
          - '*.log-api.((network_name)).((deployment_name)).bosh'
          policy-server.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          reverse-log-proxy.service.cf.internal:
          - '*.log-api.((network_name)).((deployment_name)).bosh'
          routing-api.service.cf.internal:
          - '*.api.((network_name)).((deployment_name)).bosh'
          silk-controller.service.cf.internal:
          - '*.diego-api.((network_name)).((deployment_name)).bosh'
          sql-db.service.cf.internal:
          - '*.mysql.((network_name)).((deployment_name)).bosh'
          - '*.postgres.((network_name)).((deployment_name)).bosh'
          - '*.database.((network_name)).((deployment_name)).bosh'
          ssh-proxy.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          tps.service.cf.internal:
          - '*.scheduler.((network_name)).((deployment_name)).bosh'
          uaa.service.cf.internal:
          - '*.uaa.((network_name)).cf.bosh'
        api:
          client:
            tls: ((dns_api_client_tls))
          server:
            tls: ((dns_api_server_tls))
      release: bosh-dns
    name: bosh-dns-windows2016
- type: replace
  path: /releases/-
  value:
    name: bosh-dns
    sha1: f7242b8cf5da6db583802159d28edaed80fce9a8
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.3.0
    version: 1.3.0
- type: replace
  path: /variables/-
  value:
    name: dns_api_tls_ca
    options:
      common_name: dnsApiTlsCa
      is_ca: true
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: dns_api_client_tls
    options:
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - client_auth
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: dns_api_server_tls
    options:
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - server_auth
    type: certificate
