---
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-syslog-server?
  value:
    release: log-cache
    name: log-cache-syslog-server
    properties:
      tls:
        cert: "((log_cache_syslog_tls.certificate))"
        key: "((log_cache_syslog_tls.private_key))"
      metrics:
        ca_cert: "((log_cache_syslog_server_metrics_tls.ca))"
        cert: "((log_cache_syslog_server_metrics_tls.certificate))"
        key: "((log_cache_syslog_server_metrics_tls.private_key))"
        server_name: log_cache_syslog_server_metrics

- type: replace
  path: /variables/name=log_cache_syslog_tls?
  value:
    name: log_cache_syslog_tls
    type: certificate
    options:
      ca: loggregator_ca
      common_name: doppler.service.cf.internal
      alternative_names:
        - "q-s3.doppler.default.cf.bosh"
        - "doppler.service.cf.internal"
      extended_key_usage:
        - server_auth

- type: remove
  path: /instance_groups/name=doppler/jobs/name=log-cache-nozzle?

- type: replace
  path: /addons/name=loggr-syslog-agent/jobs/name=loggr-syslog-agent/properties/aggregate_drains?
  value: "syslog-tls://doppler.service.cf.internal:6067?include-metrics-deprecated=true&ssl-strict-internal=true"

- type: replace
  path: /addons/name=loggr-syslog-agent/jobs/name=loggr-syslog-agent/properties/drain_ca_cert?
  value: "((log_cache_syslog_tls.ca))"

- type: replace
  path: /variables/name=log_cache_syslog_server_metrics_tls?
  value:
    name: log_cache_syslog_server_metrics_tls
    type: certificate
    update_mode: converge
    options:
      ca: metric_scraper_ca
      common_name: log_cache_syslog_server_metrics
      alternative_names:
      - log_cache_syslog_server_metrics
      extended_key_usage:
      - server_auth
