---
# cf-deployment uses system_domain as metron agent deployment.
# Use this to override metron agent deployment name in all jobs.
- type: replace
  path: /instance_groups/name=consul/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=nats/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=consul/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=router/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=api/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=doppler/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=log-api/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=mysql/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
- type: replace
  path: /instance_groups/name=blobstore/jobs/name=metron_agent/properties/metron_agent/deployment
  value: ((metron_agent_deployment))
